### ISSUE TITLE
Link Signup to database

### ISSUE THREAD

**Issue by Chasiwpaw** [MikeSmvl/classifieds#13]
Add function part for signup.vue so that it is linked to firebase. Compare passwords and handle errors.

**Comment by asoorkeea** [comment]
This issue is linked to #37 and we must not close this one till the #37 is completed.

**Comment by asoorkeea** [comment]
Since #37 is done, we can confirm about the registered user, in the user profile information page.
We can close this issue implemented by @neha08585 .

**Comment by asoorkeea** [comment]
The signin feature works. 

The firebase authentication module has been used for the signin process. For more information relevant to the authentication module see [Firebase](https://firebase.google.com/docs/auth/). 

More details about the flow component used in the signin will be documented in the wiki pages.

See commits related to @MikeSmvl , @neha08585 , @jeffbuonamici, @Ruthvik-Shandilya for their contribution relative to UI, logic and contents.

Component modified: Signin.vue
