### ISSUE TITLE
Implement Sign In

### ISSUE THREAD

**Issue by Chasiwpaw** [MikeSmvl/classifieds#14]
I want to get user's credentials and give them to firebase. Also, I want to receive response and handle errors if there are any.

**Comment by asoorkeea** [comment]
The signin feature works.

The firebase authentication module has been used for the signin process. For more information relevant to the authentication module see Firebase.

More details about the flow component used in the signin will be documented in the wiki pages.

See commits related to @MikeSmvl , @neha08585 , @jeffbuonamici, @Ruthvik-Shandilya for their contribution relative to UI, logic and contents.

Component modified: Signin.vue
