### ISSUE TITLE
Button to browse categories

### ISSUE THREAD

**Issue by Chasiwpaw** [MikeSmvl/classifieds#26]
I want a button that is placed either on the navigation bar or next to the search bar element that will open the page with all the categories and sub-categories of postings.

**Comment by neha08585** [comment]
i think user should also provide his location for buyer to figure out if its feasible for him to reach that location

**Comment by darkheros12** [comment]
we have a categories functionality. Thus, it is done. However, we need a button also in the navigation bar. I will make a new issue for this in sprint #4.
