### ISSUE TITLE
Protected routes and catch-all route

### ISSUE THREAD

**Issue by asoorkeea** [MikeSmvl/classifieds#29]
I want to make sure some pages like "home.vue" aren't accessible if the user is not logged in and make a catch-all route for when the user tries to access an undefined page.

**Comment by Chasiwpaw** [comment]
I think this issue hasn't been completely addressed. There are still some bugs such as when the user posts an ad.

**Comment by MikeSmvl** [comment]
@Chasiwpaw Yeah I see why there is a bug with posting an ad. (We don't verify user authentication in the routing) I will add that and the catch all page for random routes that shouldn't exist to complete the issue.

**Comment by MikeSmvl** [comment]
@Chasiwpaw I've fixed this bug and added the catch-all-route feature. If you could test this branch and close this issue, I'd appreciate it.

**Comment by Chasiwpaw** [comment]
Way better now 👍 finally a way to return back to homepage, I'm closing this.
