### ISSUE TITLE
Validating the ad form 

### ISSUE THREAD

**Issue by asoorkeea** [MikeSmvl/classifieds#31]
I would like to have some basic validation for input fields. Requiring that all the fields are written and that they are accurate is enough. For example, if it contains an email field, the app should require it to be filled and to be a valid email address. The same applies for all other fields.

**Comment by MikeSmvl** [comment]
I've added some basic validation for the ad form. It essentially requires that all fields are written and has a temporary fix for cross site scripting. (XSS)
