### ISSUE TITLE
Documenting the ad component

### ISSUE THREAD

**Issue by asoorkeea** [MikeSmvl/classifieds#33]
I would like to have documentation with reference to the ad component in our project's wiki. The documentation refers mainly to what the ad page should contain in terms of properties. For example, a title, a description, a location, a phone number, etc.

**Comment by Ruthvik-Shandilya** [comment]
We will be taking up the documentation of our complete project and include search components as well in our next upcoming sprints.

**Comment by Rez97** [comment]
yea the documentation has been completed
