### ISSUE TITLE
Documenting the user registration component

### ISSUE THREAD

**Issue by asoorkeea** [MikeSmvl/classifieds#34]
I would like to have relevant documentation with reference to the signin component in the wiki. A user story explaining what would complete our registration component is sufficient. For example, should it ask for the user's name, age, etc.

**Comment by MikeSmvl** [comment]
I'm closing this issue as the user story needed is present in our wiki page. ([User Story #1](https://github.com/MikeSmvl/classifieds/wiki/User-Stories))
