### ISSUE TITLE
Integrate PM2 module

### ISSUE THREAD

**Issue by asoorkeea** [MikeSmvl/classifieds#41]
I would like to integrate a PM2 module which is a tool for monitoring the application. It should handle clustering and load balancing.

**Comment by MikeSmvl** [comment]
@asoorkeea What exactly is this? Please provide some explanation.

**Comment by asoorkeea** [comment]
The PM2 module is used for application monitoring. Very interesting module, since it monitors the node thread, and it restarts the node automatically incase of thread crash. Also, the PM2 can be used for clustering of nodes.
I suggest to let this issue in the backlog and might be useful for application monitoring in our last sprint.

**Comment by Rez97** [comment]
yea, this has been completed
