### ISSUE TITLE
Show/hide different buttons as per login status.

### ISSUE THREAD

**Issue by neha08585** [MikeSmvl/classifieds#42]
I would like that my profile button only displays once the user is logged in. I also want the sign-in button to be hidden once the user has signed in.

**Comment by MikeSmvl** [comment]
This issue has been [solved](https://github.com/MikeSmvl/classifieds/blob/c6a971bb4ed30106cd6b6d64c40c817c9f69c830/src/App.vue). I've verified that there are no bugs and that it is written correctly.
