### ISSUE TITLE
Securely save passwords in database.

### ISSUE THREAD

**Issue by neha08585** [MikeSmvl/classifieds#45]
Currently password can be viewed in devtools while signing up/signin .
Password should flow securely(encrypted form) from application to database.

Done when:
Code changes are done to encrypt the passwords and PR is raised against dev branch.
Changes are tested.

**Comment by MikeSmvl** [comment]
I am closing this issue as passwords are securely handled by firebase as a built in feature. [This image](https://i.imgur.com/EeTxedb.png) explains firebase's hash configuration for encrypting passwords.
