### ISSUE TITLE
Home page bug

### ISSUE THREAD

**Issue by darkheros12** [MikeSmvl/classifieds#51]
I need to remove a bug that causes the user to see a registration and log in button when they are already logged in. This bug happens when the user is logged in and clicks on the "classifieds" logo on the navigation bar. Re-routing this button to the home page should solve this problem.

**Comment by Chasiwpaw** [comment]
Good catch right there, we should address this on the following sprint :+1:

**Comment by MikeSmvl** [comment]
I've fixed this issue in the dev branch. Let me know if the fix is good enough. @Chasiwpaw @darkheros12

**Comment by jeffbuonamici** [comment]
I'm closing this issue as this bug is now fixed.
