### ISSUE TITLE
Page to browse categories

### ISSUE THREAD

**Issue by MikeSmvl** [MikeSmvl/classifieds#52]
I want a page that has all the different sorts of categories and sub-categories that a user could post and they should be linked to a page that shows the items (if any) listed that pertain to the chosen category or sub-category.

**Comment by asoorkeea** [comment]
@MikeSmvl , i did some implementation to add a new category and link to an ad. I didn't see that it was link to your issue.
I made a request to merge my change in the dev. Check it out.

**Comment by MikeSmvl** [comment]
@asoorkeea Looks good, I don't see any issues except for the way the category is stored in firebase. If I make two ads with "cat" category they have different keys in the database.

**Comment by asoorkeea** [comment]
Yes, i was able to reproduce it. Strange, i'll check it out.

**Comment by asoorkeea** [comment]
As per our last meeting discussion, i made the changes. I did a cleanup to remove the categories page in the component and added a new json file to load the categories and subcategories.
However, the UI has to be ajusted in the SearchAd page to make it look nice. I have problems adjusting the UI part.
I issued a merge request in the dev. Please review.

**Comment by darkheros12** [comment]
This issue is closed.

**Comment by darkheros12** [comment]
This issue has being discussed and now it is closed
