### ISSUE TITLE
Adlist page not updating sometimes

### ISSUE THREAD

**Issue by MikeSmvl** [MikeSmvl/classifieds#53]
I would like to constantly update the "AdList.vue" page because sometimes the new ad postings don't show. Vue.js has a [page](https://vuejs.org/v2/guide/list.html#Caveats) on caveats that shows how to make arrays reactive and to solve this bug.

**Comment by darkheros12** [comment]
Yes it is completed. The page doesn't have this problem anymore. Case closed.
