### ISSUE TITLE
Integrate unit testing component

### ISSUE THREAD

**Issue by asoorkeea** [MikeSmvl/classifieds#61]
A module for unit testing will be added to the application where it will be possible to unit test our code.
An analysis of the different unit test frameworks available on the market is required and the one suitable for our application and most stable will be integrated.

**Comment by asoorkeea** [comment]
I am having an issue with performing unit testing with the firebase components. Firebase calls returns promises object. The issue is that we are not able to testing promises.
I have integrated 'chai' and 'chai-as-promised' module for the testing unfortunately it's not working.

To run the test, there are 2 files to 
1. /test/store/action2.spec.js (testcase)
2. /src/store/actions.user.js

Running the "npm run test", will execute the tests in the "action2.spec.js".
The problem is that the tests never fails once we put the expect condition in the promise object. Since it's async, it doesn't wait for the response call.

**Comment by asoorkeea** [comment]
To fix the above issue, when performing async unit testing, we need to pass an anonymous function like done to confirm that the test is completed.
For synchronous, this is not required. Besides, the chai-as-promised does not handle the asynchronous model well.

**Comment by Rez97** [comment]
yea it's done
