### ISSUE TITLE
search items

### ISSUE THREAD

**Issue by darkheros12** [MikeSmvl/classifieds#69]
The search component should get items that have the keyword in the search bar.  ie: if it has the word guitar on the title or in the description, it should retrieve the items.

**Comment by asoorkeea** [comment]
I have moved the search functionality in the actions.ad.js. 
Anyone who's going to work on this issue ping me before doing any task.

**Comment by darkheros12** [comment]
The search should be functional but it doesn't comply the requirement yet. It doesn't search for items if we do not put the entire title. it should filter the items if it contains the word.

**Comment by Chasiwpaw** [comment]
I think the most recent pull request also fixes this issue

**Comment by darkheros12** [comment]
The issue is closed. the problem is fixed.
