### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by darkheros12** [MikeSmvl/classifieds#71]
We should write a unit test for all components or improvement for the current spring

**Comment by asoorkeea** [comment]
i've added a few more unit tests for the in the ad and getters which was missing based on the coverage report uncovered lines.

**Comment by asoorkeea** [comment]
i've working in adding some unit testing for the search algorithm.

**Comment by darkheros12** [comment]
The issue is closed. The unit test for search algorithm is made.
