### ISSUE TITLE
DevOps: Required code coverage tool for application code monitoring

### ISSUE THREAD

**Issue by asoorkeea** [MikeSmvl/classifieds#73]
A code coverage tool must be put in place to provide statistics regarding the unit test code coverage and also highlighting issues newly introduced.

**Comment by asoorkeea** [comment]
Several tools are identified to perform the code coverage. The most popular tool identified are the "istanbul" babel plugins and Sonarqube.
For our application, we'll use Sonarqube which provides more functionality besides code coverage.

**Comment by Ruthvik-Shandilya** [comment]
After detailed analysis, decided to go for istanbul and nyc modules for our project. Sonarqube required much more resources in terms of memory, server and its not completely free in terms of plugins.

**Comment by asoorkeea** [comment]
Ok.
A wiki page is created which provides information regarding our implementation of code coverage or any issues encountered during the integration.
See https://github.com/MikeSmvl/classifieds/wiki/Code-Coverage

**Comment by asoorkeea** [comment]
I made some modifications to our unit tests, based on the results of the code coverage.

**Comment by asoorkeea** [comment]
We'll need to do some refactoring to the actions js, concerning the ad part and search ads.

**Comment by asoorkeea** [comment]
I'm closing this issue since we have everything that is required for code coverage. We only need to validate with our TA if the result is as expected.
